### ISSUE TITLE
Trifold Draft

### ISSUE THREAD

**Issue by zcyang123** [BIDS-collaborative/the-carpool-project#20]
[Trifold Sample.pdf](https://github.com/BIDS-collaborative/the-carpool-project/files/19914/Trifold.Sample.pdf)

@vhutheesing @sherlockjjj 
Here is the trifold draft. Please comment here so I can revise it :)

**Comment by vhutheesing** [comment]
@zcyang123 @sherlockjjj It looks really good. Here are some high-level suggestions.  Feel free to implement any that you see fit, or we can discuss them at our meeting later today.
1. Switch the order of pages 1 and 2.
2. On the new page 1, consider slightly re-ordering some of the material and try to dramatically reduce word count (by up to 50% if you can).
3. In terms of re-ordering, put Who We Are first and in this section introduce the subject of carpooling.
4. Rename the last section:  Concerns We've Already Addressed!
5. Again, if you can reduce the word count by 50% on this new page 1, that would be ideal.  I can help you in trying to accomplish this.
6. To make more space on both pages, consider removing the 3D imagery at the bottom - that way you can put the UCB affiliations further down, and of course keep the contact us link.
7.  Finally, consider adding hyperlinks to this soft copy of the user guide (I anyway don't think we need a hard copy version, but we can talk about that).  Then, readers could click over to GitHub, the App Store, the Moves download button, or to email us at The Carpool Project.

Once again, nice work!
