### ISSUE TITLE
Move link for Google drive somewhere more standard

### ISSUE THREAD

**Issue by davclark** [BIDS-collaborative/the-carpool-project#7]
The repository URL is meant to be a project info URL. For example, The [twitter bootstrap repo](https://github.com/twbs/bootstrap) links to their public facing docs site.

So, a link to google drive should go either in a text / markdown file (e.g., in the README) or in the wiki. It's confusing and presented in a "misleading" context now.

If you want less choices, move the URL to the README. The README also has way too much content.

**Comment by vhutheesing** [comment]
I have moved the URL into README and put the URL to the project's page in its place.  I still have to finish the project page this weekend.

In terms of too much content, what would you suggest I remove from README, the slides or the verbiage preceding them?

**Comment by davclark** [comment]
I can't say for sure what goes in the README or not, but I can tell you that it's longer than most people will read. Who's the audience? Usually, the README is for participants / users of the project organized in the repo.

That said, I don't think that the README is the best place to spend time now. Get some data results!
