### ISSUE TITLE
Where is data?

### ISSUE THREAD

**Issue by davclark** [BIDS-collaborative/the-carpool-project#8]
If the data is not linked or explained how to get it in the repo, then it's not available!

**Comment by vhutheesing** [comment]
Most of us have been collecting our own moves.  Only Andrea has an issue with her phone not being compatible with the Moves app.  I started on September 1st, so I have about 6 weeks worth, and have uploaded 30 days worth (all of September) to Google Doc. Others can chime in here with what they have been collecting so far.

**Comment by davclark** [comment]
But _where_ in google docs? :)

**Comment by vhutheesing** [comment]
Its in a folder in google docs named "5. Data Collection"

**Comment by davclark** [comment]
Got it! Now to get it into R or similar...
